# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c2b0617040ed31f026987b2277371a7c1424f17b47d1386f39169cf4f0eabdc03bb94fdb35cca539d3c3f1a998c148c15a34f901d942713e1a00628aa566ee9

test:
  secret_key_base: 70ee9bd2827dbc615744647bd0ca55e51b1f8e8489c0cb2e0505b7d9222e2c22b8e14b054da915dac92fad25a63fa33a4f2f97c731ddacfcf341b25268db2124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
